---
format: FSAQuarto-pdf
---

# Future State Analytics

## 2024 Services Offered

## Contact: Brendan Graham | 484-883-9211 | brendan@futurestateanalytics.io

1.  **Foundational Analytics Package**:

    -   Services: Data analysis, visualization, and basic insights.

    -   Pricing: Starting at \$2,000 per project for small businesses, with additional fees based on data volume and complexity.

    -   Deliverables

        -   Excel workbooks

        -   PowerPoint-ready tables and charts visualizations

        -   Short PDF reports

2.  **Data Visualization and Storytelling**:

    -   Services: Custom dashboard development and deep-dive analysis

    -   Pricing: Started at \$1,500 for dashboard development, \$2000 for analytics

    -   Deliverables

        -   Interactive Dashboard (web based or static)

        -   Infographics

        -   In-Depth reports

3.  **Advanced Predictive Modeling**:

    -   Services: Development of predictive models, forecasting, and optimization strategies.

    -   Pricing: Customized quotes based on project scope

    -   Deliverables

        -   Strategic report containing detailed walk through of the analysis with actionable insights

        -   A thorough evaluation report assessing the performance of the predictive models with metrics such as accuracy, precision, recall, F1-score, ROC curves, lift charts, and other relevant metrics depending on the nature of the problem being solved.

        -   Visualization of results in an interactive dashboard with report findings
        
### Timelines

Timelines are variable depending on the type of work, complexity of underlying data and analysis deliverable.
